updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'sanketmakhija'
    assignees:
      - 'sanketmakhija'
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore(deps)'
      prefix-development: 'chore(deps-dev)'
      include: 'scope'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-prerelease'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '03:00'
    reviewers:
      - 'sanketmakhija'
    labels:
      - 'ci/cd'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
